[package]
name = "macro_copy"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
pretty_assertions = "1.3.0"
proc-macro2 = "1.0.56"
quote = "1.0.27"
syn = { version = "2.0.15", features = ["extra-traits"] }
